apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-event-source
  namespace: argo-events
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: demo-argo-workflows.com
    http:
      paths:
      - path: /trigger/workflow(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: webhook-eventsource-svc
            port:
              number: 12000
