apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor
  namespace: playground
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
subjects:
- kind: ServiceAccount
  name: playground-sa
  namespace: playground
