apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-repo-config
  namespace: playground
data:
  artifactRepository: |
    s3:
      endpoint: s3-de-central.profitbricks.com:443
      bucket: customerintelligence
      region: eu-central-1
      accessKeySecret:
        name: s3-credentials
        key: accessKey
      secretKeySecret:
        name: s3-credentials
        key: secretKey